development:
  ALGOLIA_APPLICATION_ID: ""
  ALGOLIA_API_KEY: ""
  REDIS_URL: ''
  DATASET_INDEX: ''
test:
  ALGOLIA_APPLICATION_ID: ""
  ALGOLIA_API_KEY: ""
  REDIS_URL: ''
  DATASET_INDEX: ''

production:
  ALGOLIA_APPLICATION_ID: ""
  ALGOLIA_API_KEY: ""
  REDIS_URL: ''
  DATASET_INDEX: ''